server:
  port: 8090

supabase:
  url: https://veuhkewyrnuaofnanycz.supabase.co
  api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldWhrZXd5cm51YW9mbmFueWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5NjUzNDMsImV4cCI6MjEwNTU0MTM0M30.1fCbWLiTuk4kcsnLmYBnsOmyRte7r7gutVW0cnspacg
