spring:

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/game_db
    username: game_user
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8089

services:
  tic-tac-toe-engine:
    base-url:  http://192.168.1.100/game-engine/tic-tac-toe-engine/api/v1
  ludo-engine:
    base-url: http://192.168.1.100/game-engine/ludo-engine/api/v1
  tambola-engine:
    base-url: http://192.168.1.100/game-engine/tambola-engine/api/v1
    endpoints:
      start-game: /start-game
      submit-claim: /claim
      lobby: /lobby
      rules: /rules

#supabase:
 # url: https://urbbdsdaamsxtxthqxbm.supabase.co
  #api-key:


supabase:
  url: https://veuhkewyrnuaofnanycz.supabase.co
  api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldWhrZXd5cm51YW9mbmFueWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5NjUzNDMsImV4cCI6MjEwNTU0MTM0M30.1fCbWLiTuk4kcsnLmYBnsOmyRte7r7gutVW0cnspacg