server:
  port: 8085

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: hA7DnFf8vVfC3T1eZ2k7UqLbVtJ9qYgW0fP+9r5cOvQ=

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: game-service
              uri: http://192.168.1.100
              predicates:
                - Path=/api/v1/**

            - id: engine-service
              uri: http://192.168.1.100
              predicates:
                - Path=/engine/**

            - id: auth-service
              uri: http://192.168.1.100
              predicates:
                - Path=/auth/**
              filters:
                - AddRequestHeader=clientName,GAME_APP
                - AddRequestHeader=clientSecret,YzRkOWE3ZjJiMWM4N2Q1ZTlmM2ExNmI0YzhlNzUxMjM0NTY3ODkwYWJjZGVm
