spring:

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/game_db
    username: game_user
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8089

services:
  tic-tac-toe-engine:
    base-url:  http://localhost:8081/game-engine/tic-tac-toe-engine/api/v1
  ludo-engine:
    base-url: http://localhost:8081/game-engine/ludo-engine/api/v1

supabase:
  url: https://urbbdsdaamsxtxthqxbm.supabase.co
  api-key:
