spring:
  application:
    name: game-service

  datasource:
    url: jdbc:mysql://localhost:3306/game_db
    username: root
    password: Dhami@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  tictactoe-engine:
    base-url:  http://localhost:8081/api/v1/engine
    endpoints:
      start-game: /start-game
      move: /make-move

supabase:
  url: https://lmjhxwoelljmdjkbcdkp.supabase.co
  api-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtamh4d29lbGxqbWRqa2JjZGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NDAzNzIsImV4cCI6MjA5MTExNjM3Mn0.W4A57w9PqJHXq6TyMakV7sWi5ZH5EYHSlFCWCvpr5XY"

  tables:
    realtime-game-state: realtime_game_state
    realtime-game-moves: realtime_game_moves
