spring:

  datasource:
    url: jdbc:mysql://proddb:3306/game_db
    username: game_user
    password: Game@123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  server:
    port: 8080

services:
  tic-tac-toe-engine:
    base-url:  http://tic-tac-toe-engine:8080/game-engine

supabase:
  url: https://urbbdsdaamsxtxthqxbm.supabase.co
  api-key:
